# Generated by Django 3.0.6 on 2020-05-24 16:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField()),
                ('summary', models.TextField(max_length=260)),
                ('body', models.TextField()),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('published', models.DateTimeField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=50)),
            ],
        ),
    ]
