# Generated by Django 3.0.6 on 2020-05-24 06:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('title', models.CharField(help_text='Enter book title', max_length=250)),
                ('slug', models.SlugField()),
                ('summary', models.TextField(help_text='Enter a description of book', max_length=2000)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('published', models.DateTimeField()),
            ],
        ),
    ]
