# Generated by Django 3.0.6 on 2020-05-25 08:46

import blog.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.ForeignKey(null=True, on_delete=models.SET(blog.models.get_sentinel_user), to=settings.AUTH_USER_MODEL),
        ),
    ]
