# Generated by Django 3.0.6 on 2020-05-26 18:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import records.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_scale', models.CharField(max_length=6)),
                ('scale', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='MeasurableThing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(help_text='tell me about this measurable thing')),
                ('started', models.DateTimeField(auto_now_add=True)),
                ('kind', models.ForeignKey(on_delete=models.SET(records.models.get_kind), to='records.Kind')),
                ('user', models.ForeignKey(on_delete=models.SET(records.models.get_sentinel_user), to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Records',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ammount', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('measurable_thing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.MeasurableThing')),
            ],
        ),
    ]
